### ISSUE TITLE
Invalid hook call on fresh project

### ISSUE THREAD

**Issue by TimWillaert** [stephenscaff/react-animated-cursor#5]
Receiving following error:
![Screenshot_1](https://user-images.githubusercontent.com/43609662/99434315-ea2c8800-290e-11eb-94d2-f6424cbce008.jpg)
I created a project with create-react-app and installed the package through `npm i react-animated-cursor`

My App.js component just looks like this:
![Screenshot_2](https://user-images.githubusercontent.com/43609662/99434487-25c75200-290f-11eb-8c49-8444cc8f2760.jpg)

I tried clearing node_modules and npm installing again, but that doesn't help. Maybe I'm just being a dumb-dumb (I'm pretty new to React).
Really hoping to get this fixed, this looks like an awesome package!

**Comment by stephenscaff** [comment]
Sorry to hear.

Familiar with that error, but not sure where that could have originated
honestly.

I haven’t installed via CRA myself though. Will try that and see what’s up.

**Comment by TimWillaert** [comment]
Thanks for the quick response.
I started a new project without using create-react-app and it works fine now!

**Comment by stephenscaff** [comment]
Fixed. 

Tested the package with CRA (and Parcel) and runs as expected. 

You can reinstall or update to `react-animated-cursor@2.1.8`

Turns out the package _did in fact_ include its own version of React. 
Just had to move React/React Dom to dev and peer deps in <a href="https://github.com/stephenscaff/react-animated-cursor/blob/master/package.json">package.json</a>.
